// <auto-generated />
using System;
using AppsApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppsApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240411192746_seedApps")]
    partial class seedApps
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AppGenre", b =>
                {
                    b.Property<int>("AppsId")
                        .HasColumnType("int");

                    b.Property<int>("GenresId")
                        .HasColumnType("int");

                    b.HasKey("AppsId", "GenresId");

                    b.HasIndex("GenresId");

                    b.ToTable("AppGenre", (string)null);

                    b.HasData(
                        new
                        {
                            AppsId = 1,
                            GenresId = 12
                        },
                        new
                        {
                            AppsId = 1,
                            GenresId = 11
                        },
                        new
                        {
                            AppsId = 2,
                            GenresId = 1
                        },
                        new
                        {
                            AppsId = 3,
                            GenresId = 2
                        },
                        new
                        {
                            AppsId = 3,
                            GenresId = 6
                        },
                        new
                        {
                            AppsId = 4,
                            GenresId = 2
                        },
                        new
                        {
                            AppsId = 5,
                            GenresId = 8
                        },
                        new
                        {
                            AppsId = 5,
                            GenresId = 14
                        },
                        new
                        {
                            AppsId = 6,
                            GenresId = 12
                        },
                        new
                        {
                            AppsId = 6,
                            GenresId = 6
                        },
                        new
                        {
                            AppsId = 7,
                            GenresId = 5
                        },
                        new
                        {
                            AppsId = 7,
                            GenresId = 13
                        },
                        new
                        {
                            AppsId = 8,
                            GenresId = 4
                        },
                        new
                        {
                            AppsId = 8,
                            GenresId = 5
                        },
                        new
                        {
                            AppsId = 9,
                            GenresId = 8
                        },
                        new
                        {
                            AppsId = 9,
                            GenresId = 1
                        },
                        new
                        {
                            AppsId = 10,
                            GenresId = 3
                        },
                        new
                        {
                            AppsId = 10,
                            GenresId = 10
                        },
                        new
                        {
                            AppsId = 11,
                            GenresId = 6
                        },
                        new
                        {
                            AppsId = 12,
                            GenresId = 12
                        },
                        new
                        {
                            AppsId = 13,
                            GenresId = 8
                        },
                        new
                        {
                            AppsId = 14,
                            GenresId = 8
                        },
                        new
                        {
                            AppsId = 14,
                            GenresId = 11
                        },
                        new
                        {
                            AppsId = 15,
                            GenresId = 13
                        },
                        new
                        {
                            AppsId = 16,
                            GenresId = 8
                        },
                        new
                        {
                            AppsId = 16,
                            GenresId = 14
                        },
                        new
                        {
                            AppsId = 16,
                            GenresId = 9
                        },
                        new
                        {
                            AppsId = 17,
                            GenresId = 4
                        },
                        new
                        {
                            AppsId = 17,
                            GenresId = 11
                        },
                        new
                        {
                            AppsId = 17,
                            GenresId = 8
                        },
                        new
                        {
                            AppsId = 18,
                            GenresId = 5
                        },
                        new
                        {
                            AppsId = 18,
                            GenresId = 9
                        },
                        new
                        {
                            AppsId = 19,
                            GenresId = 5
                        },
                        new
                        {
                            AppsId = 19,
                            GenresId = 11
                        },
                        new
                        {
                            AppsId = 20,
                            GenresId = 1
                        },
                        new
                        {
                            AppsId = 20,
                            GenresId = 7
                        },
                        new
                        {
                            AppsId = 21,
                            GenresId = 1
                        },
                        new
                        {
                            AppsId = 21,
                            GenresId = 2
                        },
                        new
                        {
                            AppsId = 22,
                            GenresId = 6
                        },
                        new
                        {
                            AppsId = 22,
                            GenresId = 8
                        },
                        new
                        {
                            AppsId = 23,
                            GenresId = 5
                        },
                        new
                        {
                            AppsId = 23,
                            GenresId = 13
                        },
                        new
                        {
                            AppsId = 23,
                            GenresId = 6
                        },
                        new
                        {
                            AppsId = 24,
                            GenresId = 2
                        },
                        new
                        {
                            AppsId = 24,
                            GenresId = 4
                        },
                        new
                        {
                            AppsId = 25,
                            GenresId = 3
                        },
                        new
                        {
                            AppsId = 26,
                            GenresId = 8
                        },
                        new
                        {
                            AppsId = 26,
                            GenresId = 9
                        },
                        new
                        {
                            AppsId = 26,
                            GenresId = 6
                        },
                        new
                        {
                            AppsId = 27,
                            GenresId = 14
                        },
                        new
                        {
                            AppsId = 27,
                            GenresId = 12
                        },
                        new
                        {
                            AppsId = 28,
                            GenresId = 9
                        },
                        new
                        {
                            AppsId = 28,
                            GenresId = 14
                        },
                        new
                        {
                            AppsId = 29,
                            GenresId = 12
                        },
                        new
                        {
                            AppsId = 29,
                            GenresId = 6
                        },
                        new
                        {
                            AppsId = 30,
                            GenresId = 1
                        },
                        new
                        {
                            AppsId = 30,
                            GenresId = 3
                        },
                        new
                        {
                            AppsId = 31,
                            GenresId = 4
                        },
                        new
                        {
                            AppsId = 31,
                            GenresId = 8
                        },
                        new
                        {
                            AppsId = 31,
                            GenresId = 12
                        },
                        new
                        {
                            AppsId = 32,
                            GenresId = 14
                        });
                });

            modelBuilder.Entity("AppsApi.Data.Entities.App", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DeveloperId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleCardPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperId");

                    b.ToTable("Apps");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 4, 11, 22, 27, 46, 446, DateTimeKind.Local).AddTicks(4276),
                            Description = "PlayerUnknown's Battlegrounds (PUBG) is a battle royale shooter that pits 100 players against each other in a struggle for survival. Gather supplies and outwit your opponents to be the last person standing.",
                            DeveloperId = 4,
                            Price = 57.899999999999999,
                            ReleaseDate = new DateTime(2013, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "PlayerUnknown's Battlegrounds (PUBG)",
                            TitleCardPath = "https://localhost:7110/TitleCards/0.jpg"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 4, 11, 22, 27, 46, 446, DateTimeKind.Local).AddTicks(4360),
                            Description = "Counter-Strike: Global Offensive (CS:GO) is a multiplayer first-person shooter game where teams of terrorists and counter-terrorists battle it out in various game modes such as Bomb Defusal and Hostage Rescue.",
                            DeveloperId = 1,
                            Price = 82.900000000000006,
                            ReleaseDate = new DateTime(2011, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Counter-Strike: Global Offensive (CS:GO)",
                            TitleCardPath = "https://localhost:7110/TitleCards/1.jpg"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 4, 11, 22, 27, 46, 446, DateTimeKind.Local).AddTicks(4372),
                            Description = "Dota 2 is a multiplayer online battle arena (MOBA) game where two teams of five players each compete to destroy each other's Ancient, a heavily guarded structure at the opposing corner of the map.",
                            DeveloperId = 5,
                            Price = 21.899999999999999,
                            ReleaseDate = new DateTime(2022, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Dota 2",
                            TitleCardPath = "https://localhost:7110/TitleCards/2.jpg"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 4, 11, 22, 27, 46, 446, DateTimeKind.Local).AddTicks(4385),
                            Description = "Grand Theft Auto V is an action-adventure game set in the fictional state of San Andreas. Players complete missions—linear scenarios with set objectives—to progress through the story.",
                            DeveloperId = 9,
                            Price = 19.899999999999999,
                            ReleaseDate = new DateTime(2007, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Grand Theft Auto V",
                            TitleCardPath = "https://localhost:7110/TitleCards/3.jpg"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 4, 11, 22, 27, 46, 446, DateTimeKind.Local).AddTicks(4400),
                            Description = "Tom Clancy's Rainbow Six Siege is a tactical shooter game where players take on the roles of members of the Rainbow team, a counter-terrorism unit. Teamwork and strategy are key to success.",
                            DeveloperId = 1,
                            Price = 54.899999999999999,
                            ReleaseDate = new DateTime(2023, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Tom Clancy's Rainbow Six Siege",
                            TitleCardPath = "https://localhost:7110/TitleCards/4.jpg"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 4, 11, 22, 27, 46, 446, DateTimeKind.Local).AddTicks(4415),
                            Description = "Team Fortress 2 is a multiplayer first-person shooter game with cartoony graphics and a variety of character classes. Players can engage in various game modes such as Capture the Flag and King of the Hill.",
                            DeveloperId = 6,
                            Price = 15.9,
                            ReleaseDate = new DateTime(2006, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Team Fortress 2",
                            TitleCardPath = "https://localhost:7110/TitleCards/5.jpg"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 4, 11, 22, 27, 46, 446, DateTimeKind.Local).AddTicks(4428),
                            Description = "Terraria is an action-adventure sandbox game with an emphasis on exploration and crafting. Players can dig, build, fight, and explore in a procedurally generated 2D world.",
                            DeveloperId = 1,
                            Price = 55.899999999999999,
                            ReleaseDate = new DateTime(2019, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Terraria",
                            TitleCardPath = "https://localhost:7110/TitleCards/6.jpg"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 4, 11, 22, 27, 46, 446, DateTimeKind.Local).AddTicks(4441),
                            Description = "The Witcher 3: Wild Hunt is an action role-playing game set in an open world environment. Players control Geralt of Rivia, a monster hunter known as a Witcher.",
                            DeveloperId = 2,
                            Price = 17.899999999999999,
                            ReleaseDate = new DateTime(2014, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Witcher 3: Wild Hunt",
                            TitleCardPath = "https://localhost:7110/TitleCards/7.jpg"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2024, 4, 11, 22, 27, 46, 446, DateTimeKind.Local).AddTicks(4562),
                            Description = "Rocket League is a vehicular soccer video game where players control rocket-powered cars and use them to hit a ball into their opponent's goal to score points.",
                            DeveloperId = 4,
                            Price = 96.900000000000006,
                            ReleaseDate = new DateTime(1998, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Rocket League",
                            TitleCardPath = "https://localhost:7110/TitleCards/8.jpg"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2024, 4, 11, 22, 27, 46, 446, DateTimeKind.Local).AddTicks(4592),
                            Description = "Cyberpunk 2077 is an action role-playing video game set in a dystopian Night City, an open world with six distinct regions. Players assume the first-person perspective of a customizable mercenary known as V.",
                            DeveloperId = 7,
                            Price = 33.899999999999999,
                            ReleaseDate = new DateTime(1995, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Cyberpunk 2077",
                            TitleCardPath = "https://localhost:7110/TitleCards/9.jpg"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2024, 4, 11, 22, 27, 46, 446, DateTimeKind.Local).AddTicks(4606),
                            Description = "Among Us is an online multiplayer social deduction game where players work together to complete tasks on a spaceship, but beware, there are impostors among the crew.",
                            DeveloperId = 8,
                            Price = 90.900000000000006,
                            ReleaseDate = new DateTime(2007, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Among Us",
                            TitleCardPath = "https://localhost:7110/TitleCards/10.jpg"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2024, 4, 11, 22, 27, 46, 446, DateTimeKind.Local).AddTicks(4618),
                            Description = "Red Dead Redemption 2 is an action-adventure game set in an open world environment. Players control Arthur Morgan, a member of the Van der Linde gang, as he navigates the challenges of the American frontier.",
                            DeveloperId = 5,
                            Price = 71.900000000000006,
                            ReleaseDate = new DateTime(2024, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Red Dead Redemption 2",
                            TitleCardPath = "https://localhost:7110/TitleCards/11.jpg"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2024, 4, 11, 22, 27, 46, 446, DateTimeKind.Local).AddTicks(4630),
                            Description = "Fall Guys: Ultimate Knockout is a multiplayer party game where players compete in a series of challenges inspired by game shows. The goal is to be the last one standing.",
                            DeveloperId = 2,
                            Price = 91.900000000000006,
                            ReleaseDate = new DateTime(1995, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Fall Guys: Ultimate Knockout",
                            TitleCardPath = "https://localhost:7110/TitleCards/12.jpg"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2024, 4, 11, 22, 27, 46, 446, DateTimeKind.Local).AddTicks(4643),
                            Description = "Rust is a multiplayer survival game where players must scavenge for resources, build shelters, and defend themselves against hostile players and NPCs.",
                            DeveloperId = 1,
                            Price = 52.899999999999999,
                            ReleaseDate = new DateTime(2004, 7, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Rust",
                            TitleCardPath = "https://localhost:7110/TitleCards/13.jpg"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2024, 4, 11, 22, 27, 46, 446, DateTimeKind.Local).AddTicks(4657),
                            Description = "Apex Legends is a free-to-play battle royale game set in the Titanfall universe. Players select from a roster of characters, each with their own unique abilities, and compete to be the last squad standing.",
                            DeveloperId = 7,
                            Price = 82.900000000000006,
                            ReleaseDate = new DateTime(2021, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Apex Legends",
                            TitleCardPath = "https://localhost:7110/TitleCards/14.jpg"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2024, 4, 11, 22, 27, 46, 446, DateTimeKind.Local).AddTicks(4670),
                            Description = "Destiny 2 is a multiplayer first-person shooter game with elements of role-playing and MMO gameplay. Players assume the role of Guardians, protectors of humanity, and battle against alien threats.",
                            DeveloperId = 9,
                            Price = 91.900000000000006,
                            ReleaseDate = new DateTime(2017, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Destiny 2",
                            TitleCardPath = "https://localhost:7110/TitleCards/15.jpg"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2024, 4, 11, 22, 27, 46, 446, DateTimeKind.Local).AddTicks(4688),
                            Description = "Monster Hunter: World is an action role-playing game where players hunt down and defeat various monsters in a richly detailed ecosystem. Players can craft weapons and armor from materials gathered from their hunts.",
                            DeveloperId = 6,
                            Price = 12.9,
                            ReleaseDate = new DateTime(1998, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Monster Hunter: World",
                            TitleCardPath = "https://localhost:7110/TitleCards/16.jpg"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2024, 4, 11, 22, 27, 46, 446, DateTimeKind.Local).AddTicks(4795),
                            Description = "Garry's Mod is a sandbox physics game that allows players to manipulate objects and experiment with physics in a virtual environment. It features a wide range of user-generated content and game modes.",
                            DeveloperId = 7,
                            Price = 67.900000000000006,
                            ReleaseDate = new DateTime(2018, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Garry's Mod",
                            TitleCardPath = "https://localhost:7110/TitleCards/17.jpg"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2024, 4, 11, 22, 27, 46, 446, DateTimeKind.Local).AddTicks(4821),
                            Description = "ARK: Survival Evolved is a multiplayer survival game set in a world populated by dinosaurs and other prehistoric creatures. Players must hunt, gather, build shelters, and tame dinosaurs to survive.",
                            DeveloperId = 5,
                            Price = 64.900000000000006,
                            ReleaseDate = new DateTime(1999, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "ARK: Survival Evolved",
                            TitleCardPath = "https://localhost:7110/TitleCards/18.jpg"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2024, 4, 11, 22, 27, 46, 446, DateTimeKind.Local).AddTicks(4837),
                            Description = "PAYDAY 2 is a cooperative first-person shooter game where players take on the roles of masked criminals performing various heists and robberies. Team coordination and planning are essential for success.",
                            DeveloperId = 1,
                            Price = 91.900000000000006,
                            ReleaseDate = new DateTime(2009, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "PAYDAY 2",
                            TitleCardPath = "https://localhost:7110/TitleCards/19.jpg"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2024, 4, 11, 22, 27, 46, 446, DateTimeKind.Local).AddTicks(4852),
                            Description = "No Man's Sky is a procedurally generated open-world exploration game set in a vast universe. Players explore planets, gather resources, trade with alien civilizations, and uncover the mysteries of the cosmos.",
                            DeveloperId = 6,
                            Price = 88.900000000000006,
                            ReleaseDate = new DateTime(2018, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "No Man's Sky",
                            TitleCardPath = "https://localhost:7110/TitleCards/20.jpg"
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2024, 4, 11, 22, 27, 46, 446, DateTimeKind.Local).AddTicks(4867),
                            Description = "Warframe is a cooperative third-person shooter game where players control members of the Tenno, ancient warriors who have awoken from centuries of cryosleep to battle against various factions in a war-torn solar system.",
                            DeveloperId = 5,
                            Price = 41.899999999999999,
                            ReleaseDate = new DateTime(2002, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Warframe",
                            TitleCardPath = "https://localhost:7110/TitleCards/21.jpg"
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2024, 4, 11, 22, 27, 46, 446, DateTimeKind.Local).AddTicks(4884),
                            Description = "Borderlands 3 is a first-person shooter looter game set in a cel-shaded open world. Players control one of four Vault Hunters, each with their own unique abilities and playstyles, as they journey across the galaxy in search of treasure and glory.",
                            DeveloperId = 9,
                            Price = 74.900000000000006,
                            ReleaseDate = new DateTime(2002, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Borderlands 3",
                            TitleCardPath = "https://localhost:7110/TitleCards/22.jpg"
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2024, 4, 11, 22, 27, 46, 446, DateTimeKind.Local).AddTicks(4902),
                            Description = "Sekiro: Shadows Die Twice is an action-adventure game set in a fictionalized late 1500s Sengoku period Japan. Players control a shinobi known as Wolf as he embarks on a quest to rescue his kidnapped lord and seek revenge on his enemies.",
                            DeveloperId = 9,
                            Price = 83.900000000000006,
                            ReleaseDate = new DateTime(2016, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Sekiro: Shadows Die Twice",
                            TitleCardPath = "https://localhost:7110/TitleCards/23.jpg"
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2024, 4, 11, 22, 27, 46, 446, DateTimeKind.Local).AddTicks(4918),
                            Description = "Valheim is a survival and sandbox game set in a procedurally generated world inspired by Norse mythology. Players must gather resources, craft tools and weapons, build structures, and defeat enemies in order to survive and thrive in the world of Valheim.",
                            DeveloperId = 6,
                            Price = 61.899999999999999,
                            ReleaseDate = new DateTime(2006, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Valheim",
                            TitleCardPath = "https://localhost:7110/TitleCards/24.jpg"
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2024, 4, 11, 22, 27, 46, 446, DateTimeKind.Local).AddTicks(4933),
                            Description = "Football Manager 2021 is a football management simulation game where players take on the role of a football manager, controlling various aspects of their chosen club, including tactics, transfers, and team selection.",
                            DeveloperId = 4,
                            Price = 25.899999999999999,
                            ReleaseDate = new DateTime(1996, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Football Manager 2021",
                            TitleCardPath = "https://localhost:7110/TitleCards/25.jpg"
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2024, 4, 11, 22, 27, 46, 446, DateTimeKind.Local).AddTicks(5061),
                            Description = "Subnautica is an underwater survival game set on an alien planet. Players must explore the ocean depths, gather resources, and build habitats while avoiding dangerous creatures and uncovering the mysteries of the planet.",
                            DeveloperId = 4,
                            Price = 2.8999999999999999,
                            ReleaseDate = new DateTime(1998, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Subnautica",
                            TitleCardPath = "https://localhost:7110/TitleCards/26.jpg"
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2024, 4, 11, 22, 27, 46, 446, DateTimeKind.Local).AddTicks(5085),
                            Description = "Left 4 Dead 2 is a cooperative first-person shooter game where players take on the roles of survivors of a zombie apocalypse. Teamwork and coordination are essential as players fight their way through hordes of infected while completing objectives.",
                            DeveloperId = 8,
                            Price = 19.899999999999999,
                            ReleaseDate = new DateTime(2009, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Left 4 Dead 2",
                            TitleCardPath = "https://localhost:7110/TitleCards/27.jpg"
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2024, 4, 11, 22, 27, 46, 446, DateTimeKind.Local).AddTicks(5102),
                            Description = "The Elder Scrolls V: Skyrim is an action role-playing game set in the fantasy world of Tamriel. Players assume the role of the Dragonborn, a prophesied hero destined to save the world from destruction.",
                            DeveloperId = 9,
                            Price = 65.900000000000006,
                            ReleaseDate = new DateTime(2006, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Elder Scrolls V: Skyrim",
                            TitleCardPath = "https://localhost:7110/TitleCards/28.jpg"
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2024, 4, 11, 22, 27, 46, 446, DateTimeKind.Local).AddTicks(5119),
                            Description = "Halo: The Master Chief Collection is a compilation of first-person shooter games from the Halo series. Players can experience the epic story of Master Chief across multiple games and campaigns.",
                            DeveloperId = 9,
                            Price = 65.900000000000006,
                            ReleaseDate = new DateTime(2017, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Halo: The Master Chief Collection",
                            TitleCardPath = "https://localhost:7110/TitleCards/29.jpg"
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2024, 4, 11, 22, 27, 46, 446, DateTimeKind.Local).AddTicks(5138),
                            Description = "Minecraft is a sandbox game that allows players to build and explore virtual worlds made up of blocks. Players can gather resources, craft tools and items, and create structures and landscapes.",
                            DeveloperId = 1,
                            Price = 5.9000000000000004,
                            ReleaseDate = new DateTime(2005, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Minecraft",
                            TitleCardPath = "https://localhost:7110/TitleCards/30.jpg"
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2024, 4, 11, 22, 27, 46, 446, DateTimeKind.Local).AddTicks(5157),
                            Description = "Control is an action-adventure game set in a mysterious government building called the Federal Bureau of Control. Players control Jesse Faden, who possesses supernatural abilities, as she investigates paranormal phenomena and fights otherworldly enemies.",
                            DeveloperId = 6,
                            Price = 85.900000000000006,
                            ReleaseDate = new DateTime(2011, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Control",
                            TitleCardPath = "https://localhost:7110/TitleCards/31.jpg"
                        });
                });

            modelBuilder.Entity("AppsApi.Data.Entities.Developer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Developers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 4, 11, 22, 27, 46, 446, DateTimeKind.Local).AddTicks(4016),
                            Description = "Known for their challenging and immersive worlds.",
                            Name = "FroSoft",
                            ProfilePath = "https://localhost:7110/ImageProfiles/917f8e83-9fe1-430b-8e9e-0f84162389ea.png"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 4, 11, 22, 27, 46, 446, DateTimeKind.Local).AddTicks(4020),
                            Description = "Renowned for their vast open-world RPGs filled with rich lore.",
                            Name = "BethSoft",
                            ProfilePath = "https://localhost:7110/ImageProfiles/39e18c53-4ec7-430f-909b-acad430a1ad8.jpg"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 4, 11, 22, 27, 46, 446, DateTimeKind.Local).AddTicks(4021),
                            Description = "Masters of narrative-driven gameplay and memorable characters.",
                            Name = "BioWorks",
                            ProfilePath = "https://localhost:7110/ImageProfiles/2483acae-a970-43b0-b84b-1ae73b80c2e8.jpg"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 4, 11, 22, 27, 46, 446, DateTimeKind.Local).AddTicks(4022),
                            Description = "Creators of visually stunning and inventive platformers.",
                            Name = "Insomnia Games",
                            ProfilePath = "https://localhost:7110/ImageProfiles/6cd64236-ead2-4305-b984-5f9f2921e712.jpg"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 4, 11, 22, 27, 46, 446, DateTimeKind.Local).AddTicks(4023),
                            Description = "Experts in creating addictive loot-based shooter experiences.",
                            Name = "Gearworks",
                            ProfilePath = "https://localhost:7110/ImageProfiles/2e692f68-c87d-4586-8264-ec09216b907a.jpg"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 4, 11, 22, 27, 46, 446, DateTimeKind.Local).AddTicks(4025),
                            Description = "Pioneers in online multiplayer gaming and epic sci-fi universes.",
                            Name = "Bungo",
                            ProfilePath = "https://localhost:7110/ImageProfiles/ec7510ef-0e9a-4004-9bb7-9bf8ce37c816.jpg"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 4, 11, 22, 27, 46, 446, DateTimeKind.Local).AddTicks(4026),
                            Description = "Crafters of cinematic action-adventure games with depth.",
                            Name = "Sucker Punch Studios",
                            ProfilePath = "https://localhost:7110/ImageProfiles/25ad4dfc-9508-461f-a58e-468c220f401a.jpg"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 4, 11, 22, 27, 46, 446, DateTimeKind.Local).AddTicks(4027),
                            Description = "Innovators in fast-paced action gameplay and stylish visuals.",
                            Name = "Platinum Studios",
                            ProfilePath = "https://localhost:7110/ImageProfiles/e1891256-535f-4662-b60a-5b037303464c.jpg"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2024, 4, 11, 22, 27, 46, 446, DateTimeKind.Local).AddTicks(4028),
                            Description = "Visionaries known for pushing the boundaries of storytelling in games.",
                            Name = "Ko Productions",
                            ProfilePath = "https://localhost:7110/ImageProfiles/d7f74d91-bbd4-4321-8078-b1092ad2d510.jpg"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2024, 4, 11, 22, 27, 46, 446, DateTimeKind.Local).AddTicks(4030),
                            Description = "Masters of crafting immersive sandbox experiences for all ages.",
                            Name = "Playcraft",
                            ProfilePath = "https://localhost:7110/ImageProfiles/c4a0e99f-61dd-4d40-a5e9-12ed6de7f570.jpg"
                        });
                });

            modelBuilder.Entity("AppsApi.Data.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 4, 11, 22, 27, 46, 446, DateTimeKind.Local).AddTicks(3811),
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 4, 11, 22, 27, 46, 446, DateTimeKind.Local).AddTicks(3822),
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 4, 11, 22, 27, 46, 446, DateTimeKind.Local).AddTicks(3824),
                            Name = "Role-Playing Game (RPG)"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 4, 11, 22, 27, 46, 446, DateTimeKind.Local).AddTicks(3825),
                            Name = "Strategy"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 4, 11, 22, 27, 46, 446, DateTimeKind.Local).AddTicks(3826),
                            Name = "Simulation"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 4, 11, 22, 27, 46, 446, DateTimeKind.Local).AddTicks(3828),
                            Name = "Puzzle"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 4, 11, 22, 27, 46, 446, DateTimeKind.Local).AddTicks(3829),
                            Name = "Platformer"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 4, 11, 22, 27, 46, 446, DateTimeKind.Local).AddTicks(3830),
                            Name = "Racing"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2024, 4, 11, 22, 27, 46, 446, DateTimeKind.Local).AddTicks(3831),
                            Name = "Fighting"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2024, 4, 11, 22, 27, 46, 446, DateTimeKind.Local).AddTicks(3833),
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2024, 4, 11, 22, 27, 46, 446, DateTimeKind.Local).AddTicks(3834),
                            Name = "Sandbox"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2024, 4, 11, 22, 27, 46, 446, DateTimeKind.Local).AddTicks(3835),
                            Name = "Stealth"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2024, 4, 11, 22, 27, 46, 446, DateTimeKind.Local).AddTicks(3836),
                            Name = "Survival"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2024, 4, 11, 22, 27, 46, 446, DateTimeKind.Local).AddTicks(3837),
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2024, 4, 11, 22, 27, 46, 446, DateTimeKind.Local).AddTicks(3838),
                            Name = "Visual Novel"
                        });
                });

            modelBuilder.Entity("AppsApi.Data.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("AppId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("AppsApi.Data.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("AppId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Recommended")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("AppUser", b =>
                {
                    b.Property<int>("AppsLibraryId")
                        .HasColumnType("int");

                    b.Property<string>("UsersLibraryId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AppsLibraryId", "UsersLibraryId");

                    b.HasIndex("UsersLibraryId");

                    b.ToTable("UserLibrary", (string)null);
                });

            modelBuilder.Entity("AppUser1", b =>
                {
                    b.Property<int>("AppsWishlistId")
                        .HasColumnType("int");

                    b.Property<string>("UsersWishlistId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AppsWishlistId", "UsersWishlistId");

                    b.HasIndex("UsersWishlistId");

                    b.ToTable("UserWishlist", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AppsApi.Data.Entities.User", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePicture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Wallet")
                        .HasColumnType("float");

                    b.HasDiscriminator().HasValue("User");
                });

            modelBuilder.Entity("AppGenre", b =>
                {
                    b.HasOne("AppsApi.Data.Entities.App", null)
                        .WithMany()
                        .HasForeignKey("AppsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppsApi.Data.Entities.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppsApi.Data.Entities.App", b =>
                {
                    b.HasOne("AppsApi.Data.Entities.Developer", "Developer")
                        .WithMany("Apps")
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Developer");
                });

            modelBuilder.Entity("AppsApi.Data.Entities.Image", b =>
                {
                    b.HasOne("AppsApi.Data.Entities.App", "App")
                        .WithMany("Images")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("App");
                });

            modelBuilder.Entity("AppsApi.Data.Entities.Review", b =>
                {
                    b.HasOne("AppsApi.Data.Entities.App", "App")
                        .WithMany("Reviews")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AppsApi.Data.Entities.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("App");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AppUser", b =>
                {
                    b.HasOne("AppsApi.Data.Entities.App", null)
                        .WithMany()
                        .HasForeignKey("AppsLibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppsApi.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UsersLibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppUser1", b =>
                {
                    b.HasOne("AppsApi.Data.Entities.App", null)
                        .WithMany()
                        .HasForeignKey("AppsWishlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppsApi.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UsersWishlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppsApi.Data.Entities.App", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("AppsApi.Data.Entities.Developer", b =>
                {
                    b.Navigation("Apps");
                });

            modelBuilder.Entity("AppsApi.Data.Entities.User", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
